export const doctors = [
    { name: "Dr. John Smith", expertise: "Physiotherapy", city: "New York" },
    { name: "Dr. Emily Jones", expertise: "Orthopedics", city: "Los Angeles" },
    { name: "Dr. Sarah Brown", expertise: "Neurology", city: "Chicago" },
    { name: "Dr. Michael Taylor", expertise: "Chiropractor", city: "New York" },
    { name: "Dr. Linda Johnson", expertise: "Sports Therapy", city: "Los Angeles" },
    { name: "Dr. David Williams", expertise: "Physical Therapy", city: "Houston" },
    { name: "Dr. James Wilson", expertise: "Pediatric Therapy", city: "Chicago" },
    { name: "Dr. Jessica Miller", expertise: "Cardiology", city: "Dallas" },
    { name: "Dr. Richard Davis", expertise: "Geriatrics", city: "Miami" },
    { name: "Dr. Barbara Moore", expertise: "Occupational Therapy", city: "San Francisco" },
    { name: "Dr. Steven Garcia", expertise: "Sports Therapy", city: "New York" },
    { name: "Dr. Patricia Martinez", expertise: "Orthopedics", city: "Los Angeles" },
    { name: "Dr. Robert Rodriguez", expertise: "Neurology", city: "Chicago" },
    { name: "Dr. James Lee", expertise: "Chiropractor", city: "Houston" },
    { name: "Dr. Mary Gonzalez", expertise: "Pediatric Therapy", city: "Dallas" },
    { name: "Dr. Christopher Perez", expertise: "Physical Therapy", city: "San Francisco" },
    { name: "Dr. Elizabeth Brown", expertise: "Cardiology", city: "New York" },
    { name: "Dr. Charles Clark", expertise: "Geriatrics", city: "Miami" },
    { name: "Dr. Margaret Anderson", expertise: "Occupational Therapy", city: "Los Angeles" },
    { name: "Dr. Donald Wright", expertise: "Sports Therapy", city: "Chicago" },
    { name: "Dr. Susan King", expertise: "Physiotherapy", city: "Houston" },
    { name: "Dr. Thomas Hernandez", expertise: "Orthopedics", city: "Dallas" },
    { name: "Dr. Karen Scott", expertise: "Neurology", city: "San Francisco" },
    { name: "Dr. Daniel Adams", expertise: "Chiropractor", city: "New York" },
    { name: "Dr. Ruth Baker", expertise: "Sports Therapy", city: "Miami" },
    { name: "Dr. George Nelson", expertise: "Physical Therapy", city: "Los Angeles" },
    { name: "Dr. Betty Carter", expertise: "Pediatric Therapy", city: "Chicago" },
    { name: "Dr. Helen Mitchell", expertise: "Cardiology", city: "Houston" },
    { name: "Dr. Mark Roberts", expertise: "Geriatrics", city: "Dallas" },
    { name: "Dr. Dorothy Turner", expertise: "Occupational Therapy", city: "San Francisco" },
    { name: "Dr. Brian Phillips", expertise: "Physiotherapy", city: "New York" },
    { name: "Dr. Melissa Campbell", expertise: "Orthopedics", city: "Miami" },
    { name: "Dr. Paul Parker", expertise: "Neurology", city: "Los Angeles" },
    { name: "Dr. Nancy Evans", expertise: "Chiropractor", city: "Chicago" },
    { name: "Dr. Edward Edwards", expertise: "Sports Therapy", city: "Houston" },
    { name: "Dr. Maria Collins", expertise: "Physical Therapy", city: "Dallas" },
    { name: "Dr. Anthony Stewart", expertise: "Pediatric Therapy", city: "San Francisco" },
    { name: "Dr. Deborah Sanchez", expertise: "Cardiology", city: "New York" },
    { name: "Dr. Ronald Morris", expertise: "Geriatrics", city: "Miami" },
    { name: "Dr. Amanda Rogers", expertise: "Occupational Therapy", city: "Los Angeles" },
    { name: "Dr. Kenneth Reed", expertise: "Physiotherapy", city: "Chicago" },
    { name: "Dr. Cynthia Cook", expertise: "Orthopedics", city: "Houston" },
    { name: "Dr. Sandra Morgan", expertise: "Neurology", city: "Dallas" },
    { name: "Dr. Dennis Bell", expertise: "Chiropractor", city: "San Francisco" },
    { name: "Dr. Sharon Murphy", expertise: "Sports Therapy", city: "New York" },
    { name: "Dr. Larry Bailey", expertise: "Physical Therapy", city: "Miami" },
    { name: "Dr. Donna Rivera", expertise: "Pediatric Therapy", city: "Los Angeles" },
    { name: "Dr. Michelle Cooper", expertise: "Cardiology", city: "Chicago" },
    { name: "Dr. Kevin Richardson", expertise: "Geriatrics", city: "Houston" },
    { name: "Dr. Carol Cox", expertise: "Occupational Therapy", city: "Dallas" },
    { name: "Dr. Jason Howard", expertise: "Physiotherapy", city: "San Francisco" },
    { name: "Dr. Kathryn Ward", expertise: "Orthopedics", city: "New York" },
    { name: "Dr. Timothy Jenkins", expertise: "Neurology", city: "Miami" },
    { name: "Dr. Janet Perry", expertise: "Chiropractor", city: "Los Angeles" },
    { name: "Dr. Rachel Foster", expertise: "Sports Therapy", city: "Chicago" },
    { name: "Dr. Jeffrey Powell", expertise: "Physical Therapy", city: "Houston" },
    { name: "Dr. Laura Long", expertise: "Pediatric Therapy", city: "Dallas" },
    { name: "Dr. Patrick Patterson", expertise: "Cardiology", city: "San Francisco" },
    { name: "Dr. Diane Hughes", expertise: "Geriatrics", city: "New York" },
    { name: "Dr. Frank Flores", expertise: "Occupational Therapy", city: "Miami" },
    { name: "Dr. Lauren Washington", expertise: "Physiotherapy", city: "Los Angeles" },
    { name: "Dr. Eric Butler", expertise: "Orthopedics", city: "Chicago" },
    { name: "Dr. Stephanie Simmons", expertise: "Neurology", city: "Houston" },
    { name: "Dr. Stephen Foster", expertise: "Chiropractor", city: "Dallas" },
    { name: "Dr. Heather Bryant", expertise: "Sports Therapy", city: "San Francisco" },
    { name: "Dr. Joshua Barnes", expertise: "Physical Therapy", city: "New York" },
    { name: "Dr. Olivia Ross", expertise: "Pediatric Therapy", city: "Miami" },
    { name: "Dr. Angela Green", expertise: "Cardiology", city: "Los Angeles" },
    { name: "Dr. Raymond Brooks", expertise: "Geriatrics", city: "Chicago" },
    { name: "Dr. Jennifer Griffin", expertise: "Occupational Therapy", city: "Houston" },
    { name: "Dr. Walter Diaz", expertise: "Physiotherapy", city: "Dallas" },
    { name: "Dr. Christina Chapman", expertise: "Orthopedics", city: "San Francisco" },
    { name: "Dr. Craig Johnston", expertise: "Neurology", city: "New York" },
    { name: "Dr. Brittany Perez", expertise: "Chiropractor", city: "Miami" },
    { name: "Dr. Bruce Armstrong", expertise: "Sports Therapy", city: "Los Angeles" },
    { name: "Dr. Julie Rose", expertise: "Physical Therapy", city: "Chicago" },
    { name: "Dr. Carl James", expertise: "Pediatric Therapy", city: "Houston" },
    { name: "Dr. Megan Alexander", expertise: "Cardiology", city: "Dallas" },
    { name: "Dr. Christine Stewart", expertise: "Geriatrics", city: "San Francisco" },
    { name: "Dr. Jack Russell", expertise: "Occupational Therapy", city: "New York" },
    { name: "Dr. Ashley Griffin", expertise: "Physiotherapy", city: "Miami" },
    { name: "Dr. Brian Nelson", expertise: "Orthopedics", city: "Los Angeles" },
    { name: "Dr. Donna Lopez", expertise: "Neurology", city: "Chicago" },
    { name: "Dr. Shawn Henderson", expertise: "Chiropractor", city: "Houston" },
    { name: "Dr. Heather Martinez", expertise: "Sports Therapy", city: "Dallas" },
    { name: "Dr. Robert Kelly", expertise: "Physical Therapy", city: "San Francisco" },
    { name: "Dr. Barbara Adams", expertise: "Pediatric Therapy", city: "New York" },
    { name: "Dr. Adam Cook", expertise: "Cardiology", city: "Miami" },
  ];
  